use a more modern ruby
okay okay FINE.... >n>

Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
  Using Bundler 2.7.2 from Gemfile.lock BUNDLED WITH 2.7.2
  /opt/hostedtoolcache/Ruby/3.1.6/x64/bin/gem install bundler -v 2.7.2
  ERROR:  Error installing bundler:
  	bundler-2.7.2 requires Ruby version >= 3.2.0. The current ruby version is 3.1.6.
  Took   0.59 seconds
Error: The process '/opt/hostedtoolcache/Ruby/3.1.6/x64/bin/gem' failed with exit code 1

(the heck is "hostedtoolcache" tho???)