oh my god jekyll
can you stfu ToT

Run bundle exec jekyll build --baseurl "/site-wisc-sdc-fa25-team"
Configuration file: /home/runner/work/site-wisc-sdc-fa25-team/site-wisc-sdc-fa25-team/site/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/runner/work/site-wisc-sdc-fa25-team/site-wisc-sdc-fa25-team/site
       Destination: /home/runner/work/site-wisc-sdc-fa25-team/site-wisc-sdc-fa25-team/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme pages-themes/minimal
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'title':
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/default.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
Error: Process completed with exit code 1.